### PR TITLE
Add nfft

### LINKED ISSUE #67: Add missing packages
Few packages that are already there in spack and require minimal effort include :

- [x] nfft
- [x] pnfft
- [x] berkeleygw
- [ ] sparskit
- [x] etsf-io

### PR DESCRIPTION
**Pull request by iamashwin99**
Fixes #67 partially
added packages : 

- [x] nfft

### CODE REVIEW

**Comment by fangohr** [comment]
Looks good. Do we have any indication octopus picks up that depedency (nfft) correctly?

**Comment by iamashwin99** [comment]
Yes, im waiting for the CI to finish that might show it.

**Comment by iamashwin99** [comment]
On the latest CI logs we see that `etsf-io` is picked up but not the `nfft` dependency.
```shell
    <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

                           Running octopus

Version                : 12.1
Commit                 :
Build time             : Fri Mar 10 18:00:23 UTC 2023
Configuration options  : maxdim3 openmp mpi sse2 avx libxc5 libxc_fxc
Optional libraries     : cgal etsf_io metis netcdf parmetis pfft nlopt
Architecture           : x86_64
C compiler             : /home/user/spack/opt/spack/linux-debian11-x86_64_v4/gcc-10.2.1/openmpi-4.1.5-yjiwchz4jalims4tif4iicxc7zzjexco/bin/mpicc (/home/user/spack/lib/spack/env/gcc/gcc)
C compiler flags       : -g -O2
C++ compiler           : /home/user/spack/lib/spack/env/gcc/g++
C++ compiler flags     : -g -O2
Fortran compiler       : /home/user/spack/opt/spack/linux-debian11-x86_64_v4/gcc-10.2.1/openmpi-4.1.5-yjiwchz4jalims4tif4iicxc7zzjexco/bin/mpif90 (/home/user/spack/lib/spack/env/gcc/gfortran) (GCC version 10.2.1 20210110)
Fortran compiler flags : -O2 -ffree-line-length-none -fallow-argument-mismatch -fallow-invalid-boz -fopenmp

```

**Comment by fangohr** [comment]
Might be easier to do one merge request per package? Then we could merge the etsf-io already.

**Comment by iamashwin99** [comment]
New nfft versions incompatible with octopus 12. The latest release of nfft as of this issue is 3.5.3 however the most recent version supported by octopus seems to be 3.2.24. https://gitlab.com/octopus-code/octopus/-/issues/654

**Review by fangohr — APPROVED** [review]

**Pull request merged**
